### ISSUE TITLE
[Football] API throttling / pausing?

### ISSUE THREAD

**Issue by sasa-fajkovic** [api-sports/public-roadmap#100]
It's very common to have the api-football.com _pause_ when a request is made. Seems like it's some kind of additional
   throttling, then after 10-15 seconds the API responds with the data. This can happen very often (every 50 calls for
   example). Behaviour like this results in the overall decrease of performance, since we have to wait for the API to
   respond.

**Comment by api-sports** [comment]
Hi,

This roadmap is only for new features not bugs as indicated.

It is probably the ratelimit per minute that limits the number of your calls and that puts on hold the additional requests not to send them back in error

Best
