### ISSUE TITLE
[Football] Connection terminated for no reason at random times

### ISSUE THREAD

**Issue by sasa-fajkovic** [api-sports/public-roadmap#101]
Often the API will terminate the connection for no reason which results  in `java.io.IOException: Broken pipe`. I found a way around this by using resillienc4j, but this kind of behaviour is not expected from a professional API.

**Comment by api-sports** [comment]
Hi,

This roadmap is only for new features not bugs as indicated.

Please contact our support team on the dashboard for that.

Best
