### ISSUE TITLE
[Football] Return correct HTTP Status codes

### ISSUE THREAD

**Issue by sasa-fajkovic** [api-sports/public-roadmap#102]
The API pretty much always return 200, even when a resource is not found for example. 
Examples:
`https://v3.football.api-sports.io/teams?country=Banana`
`https://v3.football.api-sports.io/teams?id=99999999999`
`https://v3.football.api-sports.io/venues?id=99999999999`

even the non-existing endpoint returns a 200
Requst: https://v3.football.api-sports.io/banana
Response:
```
{
    "get": "banana",
    "parameters": [],
    "errors": {
        "endpoint": "The Banana endpoint does not exist."
    },
    "results": 0,
    "paging": {
        "current": 1,
        "total": 1
    },
    "response": []
}
```

A professional API should be able to respond with correct HTTP status codes to make communication with other applications much more transparent and easier to use. Based on the HTTP status only, I can't know if the API responds with some kind of error or not. This means that I have to implement an interceptor for each HTTP call to analyze the response and check what's inside the `errors` object (which should be an array btw, not an object - https://github.com/api-sports/public-roadmap/issues/103)

**Comment by api-sports** [comment]
Hi,

That's why we display errors in a specialized field to help users understand what the error is, such as a bad endpoint, a bad parameter etc... if at each missing data we return a 404 or another code when a parameter is wrong, the user would not necessarily know which one produces the error.

Best

**Comment by sasa-fajkovic** [comment]
Hi,

you are missunderstanding thee HTTP Status codes and how a REST API should be designed based on the answer.
* 404 should not be returned when a parameter is wrong or missing. Most likely, a 400 would be the appropriate choice. 404 is meant to be used when a resource can't be found.
Example:
If I did a GET request towards the countries/banana and a country (which is a resource in this case) with a name Banana dosn't exist, then the API should respond with 404. Passing a value as a query parameter or a path variable that doesn't exist in the system is completely normal and it's not an error. 
But if I do a request where I request teams and specify `leagueee` instead of `league`, then it's a 400 since I'm not following the API contract and I'm sending an invalid parameter to interact with it.

Using a proper HTTP status code would doesn't mean you can't return the error details. You can still return all the useful errors data while providing a correct HTTP Status code. When you're constructing the response, nothing is preventing you from changing the HTTP status code from (probably the default one) 200 to something else more appropriate and adding the body that would more clearly indicate what is wrong.
