### ISSUE TITLE
[Football] Errors object in the response to be an array

### ISSUE THREAD

**Issue by sasa-fajkovic** [api-sports/public-roadmap#103]
Example request: `https://v3.football.api-sports.io/teams?season=2021&leaguee=123`

Response:
```
{
    "get": "teams",
    "parameters": {
        "season": "2021",
        "leaguee": "123"
    },
    "errors": {
        "league": "The League field is required.",
        "leaguee": "The Leaguee field do not exist."
    },
    "results": 0,
    "paging": {
        "current": 1,
        "total": 1
    },
    "response": []
}
```

The `errors` should be an array, not an object. Even the name of the property suggest it should be an array (errors is a plural of error).

Even better improvement would be to not return an `errors` object if no error has occured?

**Comment by api-sports** [comment]
Hi,

This request has already been made, but we can not change without impacting users of the current version, so it will remain like that in V3.

Best
