### ISSUE TITLE
[Football] 250req / min limit not mentioned in the documentataion

### ISSUE THREAD

**Issue by sasa-fajkovic** [api-sports/public-roadmap#104]
There is a limit of 250 requests per minute, which is not mentioned anywhere in the documentation (or I didn't find it). If such a limit is implemented, it should be made transparent to API consumers (even before buying a licence).

I've encountered this with football data. No idea how it works with other sports.

**Comment by api-sports** [comment]
Hi,

It's indicated on the subscription page and in the documentation. 

<img width="1098" alt="1" src="https://user-images.githubusercontent.com/82181860/128130508-b4a1a0f1-ec7a-41e3-99aa-ac60be4071a1.png">

https://www.api-football.com/documentation-v3#section/Authentication/API-SPORTS-Account

Best
