### ISSUE TITLE
[Football] Martinique country missing from list of countries

### ISSUE THREAD

**Issue by sasa-fajkovic** [api-sports/public-roadmap#105]
When requesting a list of countries (`https://v3.football.api-sports.io/countries`), the API doesn't show a country `Martinique`. However, in the French league "Coupe de France" in season "2020" there is a team from that country.
Example:
```
{
   "team": {
       "id": 3258,
       "name": "Club Franciscain",
       "country": "Martinique",
       "founded": 1936,
       "national": false,
       "logo": "https://media.api-sports.io/football/teams/3258.png"
   },
   "venue": {
       "id": 2129,
       "name": "Complexe Sportif de Trianon",
       "address": "Place Charles de Gaulle",
       "city": "Le François",
       "capacity": 5000,
       "surface": "grass",
       "image": "https://media.api-sports.io/football/venues/2129.png"
   }
}
```

Martinique is a colony/teritory of France (https://en.wikipedia.org/wiki/Martinique)

**Comment by api-sports** [comment]
Hi,

This roadmap is only for new features not bugs as indicated.

Please contact our support team on the dashboard for that.

Best
