### ISSUE TITLE
[Football] Venues with missing city

### ISSUE THREAD

**Issue by sasa-fajkovic** [api-sports/public-roadmap#106]
City can also be null when requesting venues for a specific country. This doesn't make any sense since the venue has
   to be located somewhere and is not floating in space, but that's how it is. Example:

```
   {
        "id": 4246,
        "name": "Stadion Park Vladimira Nazora",
        "address": null,
        "city": null,
        "capacity": 8000,
        "surface": "grass",
        "image": "https://media.api-sports.io/football/venues/4246.png"
    }
```

**Comment by api-sports** [comment]
Hi,

This roadmap is only for new features not bugs as indicated.

Please contact our support team on the dashboard for that.

Best
