### ISSUE TITLE
[Football] Venue without a name

### ISSUE THREAD

**Issue by sasa-fajkovic** [api-sports/public-roadmap#108]
There seems to be venues without a name which is highly unlikely.

#### Germany

```
 {
        "id": 9741, 
        "name": null,
        "address": "Grünwalderstraße 114",
        "city": "München",
        "capacity": 1000,
        "surface": "artificial turf",
        "image": "https://media.api-sports.io/football/venues/9741.png"
    }
```

Just googling "Munchen Grünwalderstraße 114" indicates this is the stadium: https://www.tsv1860.de/de/kontakt.htm

**Comment by api-sports** [comment]
Hi,

This roadmap is only for new features not bugs as indicated.

Please contact our support team on the dashboard for that.

Best
