### ISSUE TITLE
Status code incorrect for baseball games in extra innings

### ISSUE THREAD

**Issue by joeygio25** [api-sports/public-roadmap#109]
Hi -

Baseball games in extra innings are being reported as status "FT" (Finished).  Example: game id 63768 from 8/4/2021. It was the top of the 10th and the feed was reporting a status of FT. To stay consistent, it would be great if the status would be "IN10" "IN11" so that we know the game is still in progress and in the 10th , 11th, etc. inning. Can you please fix this ASAP? I'll be signing up soon and need it fixed as soon as possible.  Thanks!

Also, it would be great if you could add the boolean field "winner" true/false to the feed like in the football feed. Currently, we have to compare scores, which isn't great. 

Joey

**Comment by api-sports** [comment]
Thanks, but this roadmap is only for new features not bugs/missing data.

Please report this on the support chat on our dashboard.

Best
