### ISSUE TITLE
Teams Logos

### ISSUE THREAD

**Issue by api-sports** [api-sports/public-roadmap#11]
_List of logos to add or edit :_

- 1577
- 10628
- 9969
- 2733
- 1845
- 1846
- 1850
- 1852
- 1853
- 1854
- 1855
- 1856
- 1857
- 4898
- 4899
- 14219

**Comment by iamarnas** [comment]
What's fun about team logos in your API that until then the logo for Chelsea teams is not supported examples: Chelsea (W), Chelsea U23, Chelsea U21 and the rest ... Do not use the same team logo.  I understand that it must create a new one, but in this case you already have the base logo for the same teams.  And that applies to the all teams...

**Comment by peppemas** [comment]
logo 505 is wrong (changed)

https://media.api-sports.io/football/teams/505.png

new logo: 

https://www.inter.it/binaries/content/gallery/internazionale/photos/2021/03/30/logo_im.jpg/logo_im.jpg/internazionale%3Acorpo
