### ISSUE TITLE
Create a flag to identifier team classification in playoffs

### ISSUE THREAD

**Issue by LucasViniciusPereira** [api-sports/public-roadmap#113]
Hi, It's possible create a flag in endpoint fixture to identifier team classification in playoffs, example:

League: Champions League (playoffs)

Round 1: Barcelona x PSG 
Round 2: PSG x Barcelona => (flag to identify the team classified).

**Comment by api-sports** [comment]
https://github.com/api-sports/public-roadmap/issues/33
