### ISSUE TITLE
Add extra time 

### ISSUE THREAD

**Issue by LucasViniciusPereira** [api-sports/public-roadmap#128]
Hi, It's possible add extra time in first half and second half in endpoint 'fixture'?

example:

=> First Half
status: {
  long: "First Half"
  short: "1H"
  elapsed: 45
  extra: 4
}

=> Second Half
status: {
  long: "Second Half"
  short: "2H"
  elapsed: 90
  extra: 2
}

**Comment by api-sports** [comment]
https://github.com/api-sports/public-roadmap/issues/15
