### ISSUE TITLE
The timezone parameter doenst work

### ISSUE THREAD

**Issue by NatanielBR** [api-sports/public-roadmap#143]
- Description
Looking at the prints I make a request, it is expected to return in the Europe/London (UTC) timezone (Image 1). When changing the timezone (image 2) to America/Sao_Paulo (UTC -3), the time is not changed.

- Image 1
url: https://v3.football.api-sports.io/fixtures?timezone=Europe/London&live=all
![image](https://user-images.githubusercontent.com/22733502/144228559-0420c02e-7abe-46e3-b254-2071e68691df.png)

- Image 2
url: https://v3.football.api-sports.io/fixtures?timezone=America/Sao_Paulo&live=all
![image](https://user-images.githubusercontent.com/22733502/144228841-1c8bbafe-82c3-47d3-b51c-82a2fad5526c.png)

**Comment by api-sports** [comment]
Hi,

Work great on our live tester : 

![01](https://user-images.githubusercontent.com/82181860/144230914-ab2b0918-ceb1-492c-9e5b-d43f457fcb7c.png)
![02](https://user-images.githubusercontent.com/82181860/144230917-1588b8b3-d0b5-4d2a-9e29-a8cd21609f1d.png)

Check that Postman does not keep cached data on your side which would explain that the time zone information does not change.

Info: it's not the right place to report bug, this roadmap is only for features. you can contact us via the chat on the dashboard.
