### ISSUE TITLE
[FEATURE][FOOTBALL API] Number of corners in team statistics endpoint and more info in cards key

### ISSUE THREAD

**Issue by Fr3di** [api-sports/public-roadmap#146]
I think it would be good to add "corners" statistics key for each team. It would look the same as the "goals" key with "for" and "against" keys inside and "total" and "average" keys inside of that.

`"corners": {
"for": {
"total": {},
"average": {}
},
"against": {
"total": {},
"average": {}
}
},`

Additional to that it would be nice to have more informations in the "cards" key. Not only yellow and red per minutes but also "total for", "average for", "total against", "average against" for both yellow and red cards.

**Comment by PauloMendees** [comment]
That would be great! I really need that feature
