### ISSUE TITLE
2022 wish list - improvements for football API

### ISSUE THREAD

**Issue by bairrada97** [api-sports/public-roadmap#152]
Hello I will leave here some features that could make the api better, some of them are crucial others are a nice to have, in my opinion of course.

Crucial:

-   **update a standing after a match is finished.**  We cant make the standing on our side, the api doesnt provide us data to make the standings based on each countries rules. Its a crucial thing to have, imagine last match of a season and thousands of users are going to check the standings when all matches are done to see who are the champions, they think its team A is the champions but the standings are not updated because they are only updated every hour.
- **Live Standings** - pretty much same reason.

Must Have:

- **First and Second Half Statistics**
- **playoffs calculations**

Nice to have:

-  **more data about referee** - average card shown per season for example
- **how much time left to start second half** - fixtures.period.second doesnt take into account the extra time on first half, having a timestamp when first half is over its enough.
- **add xG to statistics endpoint**

think this is what I feel like could improve, anyway
wish good 2022 to the team and keep up with good work

**Comment by kobo98** [comment]
Playoffs calculation is a must, please add to the backlog 🙏
