### ISSUE TITLE
Leagues Current Season

### ISSUE THREAD

**Issue by ivanski13** [api-sports/public-roadmap#158]
Hello
Please add current season on each leagues
etc:
league: {
id: 135
name: "Serie A"
type: "League"
logo: "https://media.api-sports.io/football/leagues/135.png"
**_current season: 2021_**

**Comment by api-sports** [comment]
This field is already present in the endpoint "leagues" : 

"response": [
{
"league": {
"id": 39,
"name": "Premier League",
"type": "League",
"logo": "https://media.api-sports.io/football/leagues/2.png"
},
"country": {
"name": "England",
"code": "GB",
"flag": "https://media.api-sports.io/flags/gb.svg"
},
"seasons": [
{
"year": 2010,
"start": "2010-08-14",
"end": "2011-05-17",
**"current": false,**
