### ISSUE TITLE
Wellington Phoenix

### ISSUE THREAD

**Issue by ivanski13** [api-sports/public-roadmap#163]

**Comment by ivanski13** [comment]
Wrong / missed Team country
team: {
id: 942
name: "Wellington Phoenix"
country: "New-Zealand" - added to fixture for Australia-A league - but  this team missed in Australian teams names
Country : new 

in this Fixture:
Fixture id: 811559
league: {
id: 188
name: "A-League"
country: "Australia"
----------------
teams: {
home: {
id: 942
name: "Wellington Phoenix"
logo: "https://media.api-sports.io/football/teams/942.png"
winner: null
}
away: {
id: 7573
name: "Western United"
logo: "https://media.api-sports.io/football/teams/7573.png"
winner: null
--------------------

**Comment by api-sports** [comment]
Hi,

As indicated in the description, this roadmap is not intended to report bugs but only for future developments.

For bugs or data problems, please contact our support on the dashboard: https://dashboard.api-football.com

Best
