### ISSUE TITLE
Wrong teams in Northern Ireland

### ISSUE THREAD

**Issue by ivanski13** [api-sports/public-roadmap#164]
pls check - https://v3.football.api-sports.io/teams?country=Northern Ireland

team: {
id: 12502
name: "Brazil U17"
country: "Northern Ireland"

and many more - all teams here is wrong

**Comment by ivanski13** [comment]
same with - Saudi Arabia

**Comment by api-sports** [comment]
Hi,

As indicated in the description, this roadmap is not intended to report bugs but only for future developments.

For bugs or data problems, please contact our support on the dashboard: https://dashboard.api-football.com

Best
