### ISSUE TITLE
Link to bookmaker

### ISSUE THREAD

**Issue by LucasViniciusPereira** [api-sports/public-roadmap#20]
Add the link to the odds on the bookmaker, is that possible?

**Comment by api-sports** [comment]
Hi,

You mean the link to the bookmaker's site?

Best

**Comment by LucasViniciusPereira** [comment]
No No, 
Link to odd for the bookmaker.
Example: www.bet365.com/market=over_under_2_5

this link is to go to the exact odd market.

**Comment by api-sports** [comment]
Oh ok, I think it's not possible to add this data for each odd

**Comment by LucasViniciusPereira** [comment]
No problemn.

Tks
