### ISSUE TITLE
Games widget data-date not working with other filters

### ISSUE THREAD

**Issue by lobbo232** [api-sports/public-roadmap#203]
It seems that when you apply both the `data-date` property, and also the `data-league` and `data-season` properties together, the games widget will always display "No Games Available".

The same happens if I only set `data-league` and `data-season`, but then use the build in date selector to change the date, the widget returns "No Games Available".

For example the below will show data as expected, however if you change the date to another date nothing is shown. If you change it back to TODAY, nothing is shown still.
```
<div id="wg-api-football-games"
     data-host="@Model.DataHost"
     data-key="@Model.ApiKey"
     data-date=""
     data-league="39"
     data-season="2021"
     data-theme=""
     data-refresh="60"
     data-show-toolbar="true"
     data-show-errors="false"
     data-show-logos="false"
     data-modal-game="true"
     data-modal-standings="true"
     data-modal-show-logos="true">
</div>
<script type="module" src="https://widgets.api-sports.io/2.0.3/widgets.js"></script>
```

Example 2:
This will not show anything. Having `data-date` set along with `data-league` and `data-season` causes the widget to break.
```
<div id="wg-api-football-games"
     data-host="@Model.DataHost"
     data-key="@Model.ApiKey"
     data-date="2022-06-17"
     data-league="39"
     data-season="2021"
     data-theme=""
     data-refresh="60"
     data-show-toolbar="true"
     data-show-errors="false"
     data-show-logos="false"
     data-modal-game="true"
     data-modal-standings="true"
     data-modal-show-logos="true">
</div>
<script type="module" src="https://widgets.api-sports.io/2.0.3/widgets.js"></script>
```

Widget example:
`data-league` and `data-season` are set, `data-date` is not. The data loads as expected.
![image](https://user-images.githubusercontent.com/17614851/174328107-b4af2fb5-97d4-405b-903d-f0fdb281fe0e.png)

Changing the date tomorrow and this is the result.
![image](https://user-images.githubusercontent.com/17614851/174328157-ab69dd98-3b9d-4cc1-b66e-152617a8d041.png)

Changing the date back to "today" doesn't work either as the `data-date` field gets set to todays date. On idealisation it is blank.

**Comment by lobbo232** [comment]
@api-sports anybody available to take a look at this?

**Comment by api-sports** [comment]
Hi,

it's normal to have no data if there is no fixtures for the selected date. League 39 (England Premier league is over for 2021 season)

If you add league + season + date, you have to select a date where fixtures take place.

Best
