### ISSUE TITLE
[BAD DATA] Team id = 572 wrong coach returned by API

### ISSUE THREAD

**Issue by artur-tamazian** [api-sports/public-roadmap#205]
Correct one should be https://en.wikipedia.org/wiki/Mircea_Lucescu. Please fix, thanks!

**Comment by artur-tamazian** [comment]
Correct coach id = 2467

**Comment by api-sports** [comment]
Hi

This roadmap is only the improvements and new features and not the bugs, for the most part we manage them directly as we see them or as they are reported by our users. To report a bug, you can do it directly from the chat on our [Dashboard](https://dashboard.api-football.com/)

best
