### ISSUE TITLE
[FOOTBALL][FEATURE]Player statistics per fixture without fixture ID

### ISSUE THREAD

**Issue by DevinSmith69** [api-sports/public-roadmap#210]
Would be great to retrieve player statistics per fixture without needing to parse the fixture ID, so have an x last number of games that goes and fetches the player stats per fixture.

The reason for this request is specifically players that are transferred into a league means I would need to go fetch all the fixtures for the player from a different league that is of no interest to the rest of the site, also means further unneeded API calls being utilized.

**Comment by api-sports** [comment]
Hi,

You can use the parameters "ids" for that : 

// Get fixture from severals fixtures {ids}
// In this request events, lineups, statistics fixture and players fixture are returned in the response
get("https://v3.football.api-sports.io/fixtures?ids=215662-215663-215664-215665-215666-215667");


Best
