### ISSUE TITLE
Series/Top Facts in football games

### ISSUE THREAD

**Issue by ivanski13** [api-sports/public-roadmap#214]
Pls add series on football games - for:
- wins/draws/loses
- over/under
- cards
- corners
- both teams to score
- clean sheets
- First to concede
- First to score
and more

example for game: **Olympiacos vs  Slovan Bratislava**

**General**
Slovan Bratislava More than 2.5 goals 5 of 5
Slovan Bratislava Less than 10.5 corners 5 of 7

Olympiacos No wins 3
Olympiacos Both teams scoring 5 of 7
Olympiacos have lost 5 of their last 6 matches (Europa League).

**Personal meetings:**
Slovan Bratislava Without clean sheet 4
Olympiacos No losses 4

**Comment by api-sports** [comment]
Hi,

You already have a part of this data in the endpoint `teams``

"goals": {
"for": {
"total": {
"home": 40,
"away": 26,
"total": 66
},
"average": {
"home": "2.1",
"away": "1.4",
"total": "1.7"
},
"minute": {
"0-15": {
"total": 4,
"percentage": "6.06%"
},
"16-30": {
"total": 17,
"percentage": "25.76%"
},
"31-45": {
"total": 11,
"percentage": "16.67%"
},
"46-60": {
"total": 13,
"percentage": "19.70%"
},
"61-75": {
"total": 10,
"percentage": "15.15%"
},
"76-90": {
"total": 8,
"percentage": "12.12%"
},
"91-105": {
"total": 3,
"percentage": "4.55%"
},
"106-120": {
"total": null,
"percentage": null
}
}
},
"against": {
"total": {
"home": 17,
"away": 19,
"total": 36
},
"average": {
"home": "0.9",
"away": "1.0",
"total": "0.9"
},
"minute": {
"0-15": {
"total": 6,
"percentage": "16.67%"
},
"16-30": {
"total": 3,
"percentage": "8.33%"
},
"31-45": {
"total": 7,
"percentage": "19.44%"
},
"46-60": {
"total": 9,
"percentage": "25.00%"
},
"61-75": {
"total": 3,
"percentage": "8.33%"
},
"76-90": {
"total": 5,
"percentage": "13.89%"
},
"91-105": {
"total": 3,
"percentage": "8.33%"
},
"106-120": {
"total": null,
"percentage": null
}
}
}
},
"biggest": {
"streak": {
"wins": 4,
"draws": 2,
"loses": 2
},
"wins": {
"home": "4-0",
"away": "0-3"
},
"loses": {
"home": "0-2",
"away": "2-0"
},
"goals": {
"for": {
"home": 5,
"away": 3
},
"against": {
"home": 2,
"away": 3
}
}
},
"clean_sheet": {
"home": 7,
"away": 6,
"total": 13
},
"failed_to_score": {
"home": 2,
"away": 6,
"total": 8
},
"penalty": {
"scored": {
"total": 10,
"percentage": "100.00%"
},
"missed": {
"total": 0,
"percentage": "0%"
},
"total": 10
},
"lineups": [
{
"formation": "4-2-3-1",
"played": 32
},
{
"formation": "3-4-1-2",
"played": 4
},
{
"formation": "3-4-2-1",
"played": 1
},
{
"formation": "4-3-1-2",
"played": 1
}
],
"cards": {
"yellow": {
"0-15": {
"total": 5,
"percentage": "6.85%"
},
"16-30": {
"total": 5,
"percentage": "6.85%"
},
"31-45": {
"total": 16,
"percentage": "21.92%"
},
"46-60": {
"total": 12,
"percentage": "16.44%"
},
"61-75": {
"total": 14,
"percentage": "19.18%"
},
"76-90": {
"total": 21,
"percentage": "28.77%"
},
"91-105": {
"total": null,
"percentage": null
},
"106-120": {
"total": null,
"percentage": null
}
},
"red": {
"0-15": {
"total": null,
"percentage": null
},
"16-30": {
"total": null,
"percentage": null
},
"31-45": {
"total": null,
"percentage": null
},
"46-60": {
"total": null,
"percentage": null
},
"61-75": {
"total": null,
"percentage": null
},
"76-90": {
"total": null,
"percentage": null
},
"91-105": {
"total": null,
"percentage": null
},
"106-120": {
"total": null,
"percentage": null
}
}
}
}
}

Best
