### ISSUE TITLE
Odds live [BETA]

### ISSUE THREAD

**Issue by prybus** [api-sports/public-roadmap#22]
Is it possible to add Live types during the match?

**Comment by Melak12** [comment]
Yes, I need live odds to be added as well.

**Comment by LucasViniciusPereira** [comment]
Hi guys, Is this feature expected to be available later this year?

**Comment by Desgan** [comment]
@api-sports  Any news when it could be completed ?

**Comment by Desgan** [comment]
Hello, any news about finishing to test this feature ?
