### ISSUE TITLE
Add "days" since last game

### ISSUE THREAD

**Issue by jMoreiraSantos** [api-sports/public-roadmap#225]
As a user of API Football, I would like to know how many days the team had since the last game (considering international tournaments such as the Champions League and domestic competitions, for instance, playing mid-week for Cup)

It's super helpful to know if a team played mid-week (even more important if the team played mid-week abroad) or if they had a full week to rest and prepare

Since API Football already has the data from all competitions played by a team, we could obtain this information via a new endpoint

**Comment by api-sports** [comment]
Hello,

you can have this information with the endpoint `fixtures?team=x&last=1&status=FT`, it will give you the last match of the team. 

Best
