### ISSUE TITLE
Get current injuries for team

### ISSUE THREAD

**Issue by JLewis1** [api-sports/public-roadmap#23]
Would love an endpoint to get current active injuries per team.

**Comment by api-sports** [comment]
Hi,

Already exist : https://www.api-football.com/documentation-v3#operation/get-injuries

// Get all available injuries from one {team} & {season}
get("https://v3.football.api-sports.io/injuries?team=85&season=2020");

Best

**Comment by ivanski13** [comment]
Possible get active only for fixture
on this link -(current season + team id - we get history of all injuries - not actual) https://v3.football.api-sports.io/injuries?season=2021&team=51

active injured possible get if use fixture id - and show on this fixture who missed (actual) - https://v3.football.api-sports.io/injuries?season=2021&fixture=731788 

not possible add  - current active injuries per team
if select team see - current active injuries per team (now see history of all injuries)
