### ISSUE TITLE
API Football - Add schedule for next FIFA World Cup phases after group matches

### ISSUE THREAD

**Issue by tanisw1** [api-sports/public-roadmap#232]
Would that be possible to include the matches scheduled for the 8th Finals, quarter-finals, semi-finals, 3rd place, and the Final, as we can see in Fifa's site?

https://www.fifa.com/fifaplus/en/match-centre?date=2022-12-04&az_competitions=17

**Comment by anthonn** [comment]
This would be a really nice feature!

A solution could be to get these fixtures only if a query parameter or similar is set. But by default without the extra query parameter the present fixture response would be the default.
Then the new function would be opt-in and backward compatible, not breaking existing solutions which cannot handle teams beeing 'null'
