### ISSUE TITLE
Add "days since last game" to "fixtures"

### ISSUE THREAD

**Issue by jMoreiraSantos** [api-sports/public-roadmap#233]
Hello,

In the Football API, are you thinking to add "days since last game" in the "fixtures" call? It's super useful to know if a team played mid-week (even more important if the team played mid-week abroad) or if they had a full week to rest and prepare

**Comment by api-sports** [comment]
Hi,

It is possible to calculate it directly by calling the endpoint `fixtures?team=x&last=1&status=FT`, with this call you get the last game that the team has played, you just have to calculate the difference between the date of the game and the moment you make this call.

Best
