### ISSUE TITLE
Documentation lacks all possible values for VAR

### ISSUE THREAD

**Issue by shmonika** [api-sports/public-roadmap#234]
As per documentation, we get only 2 possible values of VAR as mentioned below : 
<img width="641" alt="Screenshot 2022-11-24 at 10 30 45" src="https://user-images.githubusercontent.com/32198941/203748775-d6652b28-474e-410f-9e73-1a323bef2be3.png">

But in the API response, there are other values also which is possible for example this 👇🏽 
<img width="455" alt="Screenshot 2022-11-24 at 10 33 28" src="https://user-images.githubusercontent.com/32198941/203748975-29b4eac1-0c63-4b48-92a3-87c5e6ff351c.png">

Please update the documentation, or provide us the list of possible values as we need to translate them when rendering in our UI.

**Comment by api-sports** [comment]
Hi,

Should be updated during the week.

here the available var events : 

Goal cancelled
Penalty confirmed
Goal Disallowed - offside
Goal confirmed
Penalty cancelled
Goal Disallowed - handball
Goal Disallowed
Goal Disallowed - Foul
Card upgrade
Penalty awarded
Card reviewed
Red card cancelled

Best
