### ISSUE TITLE
Hockey API - Add new league for NCAA

### ISSUE THREAD

**Issue by btbenedi** [api-sports/public-roadmap#240]
Title says it all :)

Would love NCAA to be added to the Hockey API

**Comment by api-sports** [comment]
Done !

**Comment by btbenedi** [comment]
> Done !

Amazing, did not expect that fast of a turnaround

From curiousity, I noticed the chart in the live tester shows a "Livescore" endpoint, but not seeing that as an option in the endpoint list, is there one for this that I'm not seeing?

Or is it assumed that information from `/games?id=<num>` is live?
