### ISSUE TITLE
Increase frequency of pre-match odds update

### ISSUE THREAD

**Issue by funnybu** [api-sports/public-roadmap#254]
Currently update happens few times a day.
To enable realtime applications connected with pre-match odds, update few times per hour would make sense.
If this is connected with increased costs from your side, the feature could get monetized separately.

**Comment by api-sports** [comment]
Hi,

You have the endpoint odds/live for this.

Best

**Comment by funnybu** [comment]
Documentation:

> odds/live
> This endpoint returns in-play odds for fixtures in progress.

What I was asking is pre-match odds, not live odds.
