### ISSUE TITLE
First season of current league

### ISSUE THREAD

**Issue by yonex68** [api-sports/public-roadmap#30]
Is it possible to add the first season of a league when calling **/leagues?current=true** ?
With this URL there's no way to check what is the first season of a league, except making another call with the id of the league to get the first year where data is available.
Many thanks !

**Comment by api-sports** [comment]
Hi,

**/leagues?current=true** return only last season or current season, you need to call the endpoin **/leagues** without parameters if you want all seasons including the first season of a league.

Best
