### ISSUE TITLE
Feature Request : Leagues endpoint show all teams - ids

### ISSUE THREAD

**Issue by modulout** [api-sports/public-roadmap#311]
Hello guys,

Can all teams be added to the leagues' endpoint? Maybe into the seasons object where they will be different for every season. 

It would be very helpful to have the connection between leagues and teams that way.

Thanks

**Comment by api-sports** [comment]
Hi,

You already can have the teams id from a league in the endpoint "teams" like `teams?leagues=x&season=y`


Best
