### ISSUE TITLE
Euro 2020 groups in standing

### ISSUE THREAD

**Issue by oguzhankosar** [api-sports/public-roadmap#34]
Group info of 6 teams in Euro 2020 are not correct. These teams are:
 Italy, Portugal, Spain, Macedonia, Scotland, Denmark
 
 Standing response for Italy:
> "group": "Euro: Ranking of third-placed teams",

 This must be "Group A".

**Comment by api-sports** [comment]
Hi,

This roadmap is not made for bug reports as indicated in the Readme. You have to contact our support for that.

Best
