### ISSUE TITLE
New competition request: Bundesliga and 2. Bundesliga Playoffs (both German)

### ISSUE THREAD

**Issue by scotland1912** [api-sports/public-roadmap#349]
For some reason there are only the Regionalliga Playoffs (4. Division) and lower, but I can't find the ones for Bundesliga and 2. Bundesliga although they are pretty important and should be covered. If they are part of another competition, please let me know.

**Comment by jbaranski** [comment]
> For some reason there are only the Regionalliga Playoffs (4. Division) and lower, but I can't find the ones for Bundesliga and 2. Bundesliga although they are pretty important and should be covered. If they are part of another competition, please let me know.

Are you talking about the Bundesliga playoff matches for relegation / promotion? In my personal experience, it's already covered, under the Bundesliga league itself.

Make a request to the fixtures endpoint with the following parameters:
```
League: 78
Season: 2022
Date: 2023-06-01
```

You'll see a result like this:
```
...
league: {
id: 78
name: "Bundesliga"
country: "Germany"
logo: "https://media.api-sports.io/football/leagues/78.png"
flag: "https://media.api-sports.io/flags/de.svg"
season: 2022
round: "Relegation Round"
}
...
```

**Comment by api-sports** [comment]
Hi,

Relegation and Promotion round are added at the end of the competition, for the moment Bundesliga 1 & 2 are not finished, that's why fixtures are not available for the moment
