### ISSUE TITLE
Penalty shootout events [UPDATE] => Add comment "Penalty shootout" in events

### ISSUE THREAD

**Issue by krimster** [api-sports/public-roadmap#35]
Would it be possible to include as part of the events endpoint penalty shootouts

**Comment by matchratings** [comment]
I support this feature!

**Comment by User-Centric-Apps** [comment]
Hi guys, would be able to see the penalty taker name and also if that person has scored or missed?

**Comment by api-sports** [comment]
Hi, 

you have these info : 

Penalties are taken at the 120th minute and it is possible to know if it has been scored or not according to the "detail"

time: {

    elapsed: 120
    extra: 7

}
team: {

    id: 768
    name: "Italy"
    logo: "https://media.api-sports.io/football/teams/768.png"

}
player: {

    id: 873
    name: "F. Bernardeschi"

}
assist: {

        id: null
        name: null
    }
    type: "Goal"
    detail: "Penalty"
    comments: null

}
{
time: {

    elapsed: 120
    extra: 8

}
team: {

    id: 10
    name: "England"
    logo: "https://media.api-sports.io/football/teams/10.png"

}
player: {

    id: 18
    name: "J. Sancho"

}
assist: {

    id: null
    name: null

}
type: "Goal"
detail: "Missed Penalty"
comments: null

**Comment by matchratings** [comment]
Thanks!
Is there a parameter that differentiates between a normal penalty and a
"kicks from the spot" tiebreaker? It appears that a penalty occurring in
first minute of stoppage time in extra time would generate the
same response as the first of the kicks from the spot, specifically:
elapsed:120, elapsed-plus:1. I can write the logic that detects multiple
penalties in a row at elapsed:120, but I want to know that I'm not missing
an easier way.

**Comment by api-sports** [comment]
Yes, we will see if it is possible to add an additional information to specify it

**Comment by api-sports** [comment]
You have now "Penalty Shootout" in the "comments" field 

==> 

`{
time: {

    elapsed: 120
    extra: 5

}
team: {

    id: 768
    name: "Italy"
    logo: "https://media.api-sports.io/football/teams/768.png"

}
player: {

    id: 853
    name: "L. Bonucci"

}
assist: {

        id: null
        name: null
    }
    type: "Goal"
    detail: "Penalty"
    comments: "Penalty Shootout"

}
{
time: {

    elapsed: 120
    extra: 6

}
team: {

    id: 10
    name: "England"
    logo: "https://media.api-sports.io/football/teams/10.png"

}
player: {

    id: 909
    name: "M. Rashford"

}
assist: {

        id: null
        name: null
    }
    type: "Goal"
    detail: "Missed Penalty"
    comments: "Penalty Shootout"

}`

**Comment by matchratings** [comment]
thank you!

**Comment by User-Centric-Apps** [comment]
Thank you!!

Much appreciated!
