### ISSUE TITLE
[football api] missing rounds for cups/ leagues

### ISSUE THREAD

**Issue by nikto1** [api-sports/public-roadmap#368]
When you call the fixtures/rounds endpoint not all rounds are available beforehand, only for regular seasons (i think, didn't test all leagues for regular seasons)
E.g. if you call the end point with the params 2024 for year and 137 for the league there are only 
`    0: "Preliminary Round"
    1: "1st Round"
    2: "2nd Round"`

the others are missing (as of writing) but are already known: _Round of 16, Quarter-finals Semi-finals_ and _Final_

Could you please add all rounds beforehand for all leagues/ cups?

**Comment by api-sports** [comment]
Hi, there, 

The rounds available in the endpoint “fixtures/rounds” correspond to the fixtures available in the endpoint “fixtures” so if the matches of the 8th final are not yet available it is normal not to have the round available in the endpoint “fixtures/rounds” it will be added once the matches are available in the API.

Best
