### ISSUE TITLE
The .png file extension is specified for player photos, but the background is not transparent

### ISSUE THREAD

**Issue by generalov-viktar** [api-sports/public-roadmap#37]
The .png file extension is specified for player photos, but the background is not transparent

For example, https://media.api-sports.io/football/players/72.png

**Comment by generalov-viktar** [comment]
And teams logo is not transparent. 
For example, https://media.api-sports.io/football/teams/165.png

**Comment by thenashone** [comment]
I'm not sure there ment to have transparent backgrounds.  they might use png for the file size to image quality.

**Comment by generalov-viktar** [comment]
> I'm not sure the images are ment to have transparent backgrounds. they might use .png for the file size and image quality.

You only need to use png for a transparent background, otherwise you need to use jpg. Thus, the file will be smaller.
