### ISSUE TITLE
Football Player co-ordinates for lineups

### ISSUE THREAD

**Issue by P8M3** [api-sports/public-roadmap#39]
Can we please have the x,y co-ordinates for lineups so we can show the starting formation.

Thank you

**Comment by api-sports** [comment]
Currently being tested: 

{
    "get": "fixtures/lineups",
    "parameters": {
        "fixture": "571844"
    },
    "errors": [],
    "results": 2,
    "paging": {
        "current": 1,
        "total": 1
    },
    "response": [
        {
            "team": {
                "id": 106,
                "name": "Stade Brestois 29",
                "logo": "https://media.api-sports.io/football/teams/106.png"
            },
            "formation": "4-4-2",
            "startXI": [
                {
                    "player": {
                        "id": 20541,
                        "name": "Gautier Larsonneur",
                        "number": 1,
                        "pos": "G",
                        "grid": "1:1"
                    }
                },
                {
                    "player": {
                        "id": 20547,
                        "name": "Julien Faussurier",
                        "number": 22,
                        "pos": "D",
                        "grid": "2:4"
                    }
                },
                {
                    "player": {
                        "id": 20546,
                        "name": "Brendan Chardonnet",
                        "number": 5,
                        "pos": "D",
                        "grid": "2:3"
                    }
                },
                {
                    "player": {
                        "id": 20655,
                        "name": "Jean-Kevin Duverne",
                        "number": 2,
                        "pos": "D",
                        "grid": "2:2"
                    }
                },
                {
                    "player": {
                        "id": 20600,
                        "name": "Romain Perraud",
                        "number": 18,
                        "pos": "D",
                        "grid": "2:1"
                    }
                },
                {
                    "player": {
                        "id": 84082,
                        "name": "Romain Faivre",
                        "number": 21,
                        "pos": "M",
                        "grid": "3:4"
                    }
                },
                {
                    "player": {
                        "id": 20558,
                        "name": "Hugo Magnetti",
                        "number": 27,
                        "pos": "M",
                        "grid": "3:3"
                    }
                },
                {
                    "player": {
                        "id": 20554,
                        "name": "Haris Belkebla",
                        "number": 7,
                        "pos": "M",
                        "grid": "3:2"
                    }
                },
                {
                    "player": {
                        "id": 20784,
                        "name": "Franck Honorat",
                        "number": 9,
                        "pos": "M",
                        "grid": "3:1"
                    }
                },
                {
                    "player": {
                        "id": 20563,
                        "name": "Gaëtan Charbonnier",
                        "number": 10,
                        "pos": "F",
                        "grid": "4:2"
                    }
                },
                {
                    "player": {
                        "id": 3395,
                        "name": "Steve Mounié",
                        "number": 15,
                        "pos": "F",
                        "grid": "4:1"
                    }
                }
            ],
            "substitutes": [
                {
                    "player": {
                        "id": 2941,
                        "name": "Mouez Hassen",
                        "number": 40,
                        "pos": "G",
                        "grid": null
                    }
                },
                {
                    "player": {
                        "id": 2193,
                        "name": "Ludovic Baal",
                        "number": 24,
                        "pos": "D",
                        "grid": null
                    }
                },
                {
                    "player": {
                        "id": 126757,
                        "name": "Lilian Brassier",
                        "number": 3,
                        "pos": "D",
                        "grid": null
                    }
                },
                {
                    "player": {
                        "id": 99,
                        "name": "Ronaël Pierre-Gabriel",
                        "number": 20,
                        "pos": "D",
                        "grid": null
                    }
                },
                {
                    "player": {
                        "id": 20565,
                        "name": "Ferris N'Goma",
                        "number": 19,
                        "pos": "M",
                        "grid": null
                    }
                },
                {
                    "player": {
                        "id": 85772,
                        "name": "Jérémy Le Douaron",
                        "number": 26,
                        "pos": "F",
                        "grid": null
                    }
                },
                {
                    "player": {
                        "id": 9994,
                        "name": "Jean Lucas",
                        "number": 6,
                        "pos": "M",
                        "grid": null
                    }
                },
                {
                    "player": {
                        "id": 129680,
                        "name": "Hianga'a M'Bock",
                        "number": 28,
                        "pos": "M",
                        "grid": null
                    }
                },
                {
                    "player": {
                        "id": 8683,
                        "name": "Irvin Cardona",
                        "number": 14,
                        "pos": "F",
                        "grid": null
                    }
                }
            ],
            "coach": {
                "id": 34,
                "name": "O. Dall’Oglio",
                "photo": "https://media.api-sports.io/football/coachs/34.png"
            }
        },
        {
            "team": {
                "id": 85,
                "name": "Paris Saint Germain",
                "logo": "https://media.api-sports.io/football/teams/85.png"
            },
            "formation": "4-3-3",
            "startXI": [
                {
                    "player": {
                        "id": 731,
                        "name": "Keylor Navas",
                        "number": 1,
                        "pos": "G",
                        "grid": "1:1"
                    }
                },
                {
                    "player": {
                        "id": 260,
                        "name": "Colin Dagba",
                        "number": 31,
                        "pos": "D",
                        "grid": "2:4"
                    }
                },
                {
                    "player": {
                        "id": 257,
                        "name": "Marquinhos",
                        "number": 5,
                        "pos": "D",
                        "grid": "2:3"
                    }
                },
                {
                    "player": {
                        "id": 262,
                        "name": "Presnel Kimpembe",
                        "number": 3,
                        "pos": "D",
                        "grid": "2:2"
                    }
                },
                {
                    "player": {
                        "id": 7,
                        "name": "Abdou Diallo",
                        "number": 22,
                        "pos": "D",
                        "grid": "2:1"
                    }
                },
                {
                    "player": {
                        "id": 898,
                        "name": "Ander Herrera",
                        "number": 21,
                        "pos": "M",
                        "grid": "3:3"
                    }
                },
                {
                    "player": {
                        "id": 381,
                        "name": "Danilo Pereira",
                        "number": 15,
                        "pos": "M",
                        "grid": "3:2"
                    }
                },
                {
                    "player": {
                        "id": 142,
                        "name": "Rafinha Alcântara",
                        "number": 12,
                        "pos": "M",
                        "grid": "3:1"
                    }
                },
                {
                    "player": {
                        "id": 266,
                        "name": "Ángel Di María",
                        "number": 11,
                        "pos": "F",
                        "grid": "4:3"
                    }
                },
                {
                    "player": {
                        "id": 278,
                        "name": "Kylian Mbappé",
                        "number": 7,
                        "pos": "F",
                        "grid": "4:2"
                    }
                },
                {
                    "player": {
                        "id": 276,
                        "name": "Neymar",
                        "number": 10,
                        "pos": "F",
                        "grid": "4:1"
                    }
                }
            ],
            "substitutes": [
                {
                    "player": {
                        "id": 19014,
                        "name": "Sergio Rico",
                        "number": 16,
                        "pos": "G",
                        "grid": null
                    }
                },
                {
                    "player": {
                        "id": 530,
                        "name": "Mitchel Bakker",
                        "number": 25,
                        "pos": "D",
                        "grid": null
                    }
                },
                {
                    "player": {
                        "id": 261,
                        "name": "Thilo Kehrer",
                        "number": 4,
                        "pos": "D",
                        "grid": null
                    }
                },
                {
                    "player": {
                        "id": 271,
                        "name": "Leandro Paredes",
                        "number": 8,
                        "pos": "M",
                        "grid": null
                    }
                },
                {
                    "player": {
                        "id": 2990,
                        "name": "Idrissa Gueye",
                        "number": 27,
                        "pos": "M",
                        "grid": null
                    }
                },
                {
                    "player": {
                        "id": 2056,
                        "name": "Pablo Sarabia",
                        "number": 19,
                        "pos": "M",
                        "grid": null
                    }
                },
                {
                    "player": {
                        "id": 267,
                        "name": "Julian Draxler",
                        "number": 23,
                        "pos": "M",
                        "grid": null
                    }
                },
                {
                    "player": {
                        "id": 216,
                        "name": "Mauro Icardi",
                        "number": 9,
                        "pos": "F",
                        "grid": null
                    }
                },
                {
                    "player": {
                        "id": 877,
                        "name": "Moise Kean",
                        "number": 18,
                        "pos": "F",
                        "grid": null
                    }
                }
            ],
            "coach": {
                "id": 13,
                "name": "M. Pochettino",
                "photo": "https://media.api-sports.io/football/coachs/13.png"
            }
        }
    ]
}

**Comment by P8M3** [comment]
Thanks for this. So it seems that the "grid" locations will be determined by "formation" which consists of 4 rows (GK, defense, mid and attack). 

Will this account for formations that only consist of 3 digits (4-3-3 for example) or will it take in to account formations that have 4 or more digits (4-3-1-2 or 3-2-3-2 for example) where attacking midfielders play higher than defensive midfielders?

Thanks

**Comment by api-sports** [comment]
this will take into account all possible formations, In the example given there was a 4-3-3 formation.
x = row and y = column (x:y)

line 1 (x) being the one of the goal and then for each line this number is incremented. The column (Y) will go from left to right, and incremented for each player of the line.

In this way it will cover all possible compositions.

if i take your example : 3-2-3-2 this will be =>
1:1 => Goal
2:1
2:2
2:3
3:1
3:2
4:1
4:2
4:3
5:1
5:2

**Comment by P8M3** [comment]
That's great. I look forward to the release of this.

**Comment by P8M3** [comment]
I am watching this like a hawk. I don't mean to rush you but do you have a rough idea of when this feature will be available?
Just so that I can plan when to release my next update.

Thanks

**Comment by api-sports** [comment]
We are doing our best to make it available before the end of the week, but we still have some testing and documentation to update.

**Comment by api-sports** [comment]
![1](https://user-images.githubusercontent.com/82181860/121214497-74264900-c87f-11eb-970b-e012ab7fcabd.jpg)
![2](https://user-images.githubusercontent.com/82181860/121214519-78eafd00-c87f-11eb-838f-fadb2cb55233.jpg)
