### ISSUE TITLE
PLAYERS SQUAD : Current club team player is assosciated with

### ISSUE THREAD

**Issue by rahulp959** [api-sports/public-roadmap#40]
Hey there,

Would it be possible to have a link between a player and a team, or even an array of their current national team and club team?

Or the other way around where getting a team gets you a list of their current players?

Thanks!

**Comment by generalov-viktar** [comment]
> Hey there,
> 
> Would it be possible to have a link between a player and a team, or even an array of their current national team and club team?
> 
> Or the other way around where getting a team gets you a list of their current players?
> 
> Thanks!

Hi, you can call the players method and specify the team id and the year of the season (2020) and you will get a list of the team's players.

Documentation: https://www.api-football.com/documentation-v3#operation/get-players

**Comment by rahulp959** [comment]
Appreciate the response!

I was specifically thinking players _currently_ tied to the team, for instance that request with a team of 37 and season of 2020 would return Lingard as a Manchester United player, which as of this moment he _technically_ isn't.

Is there a possibility of a way to filter these out more easily?

**Comment by thenashone** [comment]
I was looking to add this, but found a temperary walkround.

im using the fixtures lineups to query this.

But!!! im no pro just learing things myself.

**Comment by rahulp959** [comment]
Hmmm, yeah -- I've been debating using the players by team/league search, and then checking the transfers for the player, stripping out any that are in the future and then picking the last record and recording their "in" team

**Comment by thenashone** [comment]
only problem i can see is if someone goes on loan abroad then we have to search the each country team and fixtures lol.

**Comment by rahulp959** [comment]
@api-sports 

Any thoughts on the above?

**Comment by thenashone** [comment]
@rahulp959  I have been thinking and found a faster way to loop this..

if you search player by team and follow the player id you will get the  current team from the statistics.

example: lingard player_id is 900

statistics - > team - > name (West Ham)

**Comment by rahulp959** [comment]
Yes, but is that guaranteed as soon as the transfer goes through? That same statistics also has Manchester United for the same season

**Comment by api-sports** [comment]
https://www.api-football.com/documentation-v3#operation/get-players-squads
