### ISSUE TITLE
Get current season for club

### ISSUE THREAD

**Issue by JLewis1** [api-sports/public-roadmap#48]
There's no way to tell what the current season is for any given club. Some leagues are 2021 and some leagues are 2020. I'd like to include the current season in the get teams call. So that I can use the current season to get the latest leagues, coaches, players etc.

**Comment by api-sports** [comment]
Hi,

This endpoint can meet your needs ==> https://www.api-football.com/documentation-v3#operation/get-teams-seasons

I you keep only the last season in the response you have the current season.

Best
