### ISSUE TITLE
Player distance on player match statistics

### ISSUE THREAD

**Issue by thenashone** [api-sports/public-roadmap#51]
I am not sure if its possible or even be usefull to others, a feature i would love to see is have the player distance traveled in the match stats

example.

```
statistics: [
{
games: {

    minutes: 90
    number: 1
    position: "G"
    rating: "5.9"
    distance: 10.8 kilometers
    captain: false
    substitute: false

}
```

Just an idea feel free to delete this  :)

**Comment by api-sports** [comment]
This is a good idea, unfortunately we don't have the data to do this.

**Comment by thenashone** [comment]
thank-you for the reply :)
