### ISSUE TITLE
Group of fixture

### ISSUE THREAD

**Issue by xtazy** [api-sports/public-roadmap#52]
Hello,

It would be interesting to also have the group that a fixture belongs to. (if applicable)

For example, if I take 'Ligue 2 - 2020' in Tunisia, there are 4 groups in the regular season (group A, B, C and D), but the API doesn't give the group, so all the fixtures appear as one unit (under round = Regular Season), which is wrong.

**Comment by api-sports** [comment]
Hi,

For this league, groups are available in the "standings" endpoint.

Best

**Comment by api-sports** [comment]
Yes, it is possible, if you match the team_id in the standings and for each group with the team_id in the endpoint fixtures.

This implies two calls to the API but is totally feasible
