### ISSUE TITLE
Lack of stats

### ISSUE THREAD

**Issue by talon023** [api-sports/public-roadmap#53]
Dear API-Sports, 

do You plan to add total corners + total shots + historical odds?

Total shots and total corners are the most scarce stats, my prediction model barely predicts any matches. 

Much Obliged!

**Comment by api-sports** [comment]
Hi,

these statistics are already available ==> https://www.api-football.com/documentation-v3#operation/get-fixtures-statistics

"statistics": [

{

    "type": "Shots on Goal",
    "value": 3

},
{

    "type": "Shots off Goal",
    "value": 2

},
{

    "type": "Total Shots",
    "value": 9

},
{

    "type": "Blocked Shots",
    "value": 4

},
{

    "type": "Shots insidebox",
    "value": 4

},
{

    "type": "Shots outsidebox",
    "value": 5

},
{

    "type": "Fouls",
    "value": 22

},
{

    "type": "Corner Kicks",
    "value": 3

},
{

    "type": "Offsides",
    "value": 1

},
{

    "type": "Ball Possession",
    "value": "32%"

},
{

    "type": "Yellow Cards",
    "value": 5

},
{

    "type": "Red Cards",
    "value": 1

},
{

    "type": "Goalkeeper Saves",
    "value": null

},
{

    "type": "Total passes",
    "value": 242

},
{

    "type": "Passes accurate",
    "value": 121

},
{

    "type": "Passes %",
    "value": null

}

For historical odds, it's not planned right now.

Best
