### ISSUE TITLE
Missing Score Result for Half-Time Period

### ISSUE THREAD

**Issue by Melak12** [api-sports/public-roadmap#54]
For some fixtures, the API returns "NULL" to half-time results. 

![image](https://user-images.githubusercontent.com/45941116/121348855-895bb000-c931-11eb-854e-f20381d5e9e5.png)

**Comment by api-sports** [comment]
Hi, 

This is not a new feature.

Not all competitions have all the functionality of the API, for some data are not available or updated in real time as indicated in the documentation

best

**Comment by Melak12** [comment]
Hello API-SPORTS Team,
We are using your API for the sports betting business in Ethiopia (
http://shegabet.com). Sometimes the data are not reliable which is risky to
our business.
Shall we keep using your API in anticipation of future improvement?
For this case, we are not requesting real-time data but the data for past
events. However, half-time data are missing for a number of fixtures.
Warm Regards*,*

*Melake*
