### ISSUE TITLE
Add promotion and relegation endpoint for teams

### ISSUE THREAD

**Issue by radtki** [api-sports/public-roadmap#56]
Hi,
i would be nice to have the promoted and relegated teams per league and season. Actually, i can't find this information from the existing endpoints.

**Comment by api-sports** [comment]
Hi,

These information can be found in the standings endpoint.

Best

**Comment by radtki** [comment]
Hello,

the value "Rank" from endpoint standings isn't the same. Therefore I do not know if the team is promoted or relegated. And in addition, many leagues have playoffs for playing a 3rd relegated or promoted team, for example the german "Bundesliga". Therefore the endpoint is not providing the data needed.
