### ISSUE TITLE
add statistics and events on H2H and fixtures

### ISSUE THREAD

**Issue by bairrada97** [api-sports/public-roadmap#63]
Currently there is no way to get statistics and events from previous games of a team.
Fixtures/statistics only let me get a single match,  there is no Last option.
 fixtures?team=""&last="" do not return statistics and events.

I want to get statistics and events from last 5 games of each team and h2h and since Im already calling h2h endpoint and fixtures?team=""&last="" would be nice to add statistics and events to both endpoints.

**Comment by api-sports** [comment]
Hi,

You have the parameters "ids" in fixtures endpoint that you can use to do this

==> https://www.api-football.com/documentation-v3#tag/Fixtures/operation/get-fixtures

// Get fixture from severals fixtures {ids}
// In this request events, lineups, statistics fixture and players fixture are returned in the response
get("https://v3.football.api-sports.io/fixtures?ids=215662-215663-215664-215665-215666-215667");
