### ISSUE TITLE
Endpoint for last team games

### ISSUE THREAD

**Issue by LucasViniciusPereira** [api-sports/public-roadmap#71]
Hi, 

It would be possible to provide an endpoint to search for the last 10, 20, 30 games of the independent team in the championship, the number of games could be a parameter, I find this interesting to display the last games of that team, would it be possible?

**Comment by api-sports** [comment]
This endpoint already exist.

==>https://www.api-football.com/documentation-v3#operation/get-fixtures

Params "team" and "last"

Best
