### ISSUE TITLE
Add World Junior Ice Hockey Championships (WJHC) to hockey API

### ISSUE THREAD

**Issue by gustavFransson** [api-sports/public-roadmap#73]
World Junior Ice Hockey Championships is arguably a bigger tournament than World Hockey Championship therefore it would be a nice feature to have World Junior Ice Hockey Championships for the hockey API.

**Comment by api-sports** [comment]
Hi, this roadmap is only for new features and not for the data available in the API.

Concerning the competitions, all the ones we have are already in our API, if a competition is not there it's because we don't have the data to provide it (this is not definitive of course)

Best
