### ISSUE TITLE
Logo update

### ISSUE THREAD

**Issue by TheoTheoQ** [api-sports/public-roadmap#81]
Hi, is it possible to update the logos for:

The leagues: ID 61 and 62

The teams: ID 77 - 78 - 93 - 87 - 112 ?
(in V3)
thank you so much

**Comment by thenashone** [comment]
@TheoTheoQ hi im not part of api-sports but i done the club badges for you. [get them here](https://drive.google.com/drive/folders/1Q9xXO00QGH_LhJvWxIYtw_GAYNngS6OH?usp=sharing)

**Comment by thenashone** [comment]
And [here](https://drive.google.com/drive/folders/1rbQDnGuBLJsNX32s8Yk38tk1asgo0nhg?usp=sharing) are the leagues you requested

**Comment by thenashone** [comment]
@TheoTheoQ sorry forgot the share settings you should beable to get them now
