### ISSUE TITLE
Add first leg/second leg information in Fixture info

### ISSUE THREAD

**Issue by JLewis1** [api-sports/public-roadmap#87]
There is nothing to indicate if a fixture is leg 1 or leg 2 of a tie. Would like to get that information, and also if it's the second leg, bring the aggregate score to the current game's data.

**Comment by api-sports** [comment]
Hi,

Already exist ==> [https://github.com/api-sports/public-roadmap/issues/33](https://github.com/api-sports/public-roadmap/issues/33)
