### ISSUE TITLE
[Football] Incorrect match status

### ISSUE THREAD

**Issue by sasa-fajkovic** [api-sports/public-roadmap#96]
For some matches, API returns an incorrect status. Instead of `CANC` it returns `Canc`. 

I don't remember the match ID, but you can easily find it by querying your database. It's probably safe to assume there is a same issue with other match statuses

**Comment by api-sports** [comment]
Hi,

This roadmap is only for new features not bugs as indicated.

Please contact our support team on the dashboard for that.

Best
