### ISSUE TITLE
[Football] Venue data missing when requesting venue by id (7173)

### ISSUE THREAD

**Issue by sasa-fajkovic** [api-sports/public-roadmap#97]
When requesting matches for:
`https://v3.football.api-sports.io/fixtures?season=2019&league=482`

we get venue with an id 7173 for some matches. However, when, requesting details for that venue (`https://v3.football.api-sports.io/venues?id=7173`), the API returns no data:
```
{
    "get": "venues",
    "parameters": {
        "id": "7173"
    },
    "errors": [],
    "results": 0,
    "paging": {
        "current": 1,
        "total": 1
    },
    "response": []
}
```

**Comment by api-sports** [comment]
Hi,

This roadmap is only for new features not bugs as indicated.

Please contact our support team on the dashboard for that.

Best
