### ISSUE TITLE
[Football] List of teams returns teams without country

### ISSUE THREAD

**Issue by sasa-fajkovic** [api-sports/public-roadmap#98]
When requesting `https://v3.football.api-sports.io/teams?league=768&season=2019` we get some teams that don't have a country associated with them.
Example:
```
"team": {
                "id": 16194,
                "name": "ASAS",
                "country": null,
                "founded": null,
                "national": false,
                "logo": "https://media.api-sports.io/football/teams/16194.png"
            },
```

**Comment by api-sports** [comment]
Hi,

This roadmap is only for new features not bugs as indicated.

Please contact our support team on the dashboard for that.

Best
