### ISSUE TITLE
[Football] Costa-Rica instead of Costa Rica

### ISSUE THREAD

**Issue by sasa-fajkovic** [api-sports/public-roadmap#99]
When retrieving a list of countries (`https://v3.football.api-sports.io/countries`), the API returns a country `Costa Rica`.

Some teams have assosiated with them a different name (Costa-Rica)
Example: `https://v3.football.api-sports.io/teams?country=Costa-Rica`

Expected behaviour would be to have a consistent country name.

**Comment by api-sports** [comment]
Hi,

This roadmap is only for new features not bugs as indicated.

Please contact our support team on the dashboard for that.

Best
